---
# - name: Install SELinux files
#   dnf:
#     name: libselinux-python
#     state: present
#     disablerepo: fedora-modular-server,fedora-modular-server-updates-testing

- name: Create system profile directory
  file:
    path: /etc/dnf/modules.defaults.d
    state: directory
    mode: 0755

- name: Move system profile to appropriate directory
  copy: src=base-28.defaults dest=/etc/dnf/modules.defaults.d/base-28.defaults 

#this does not seem to work, disable_gpg_check not being honored?
# also, i need "dnf update" and this runs "dnf install"
# - name: Install correct repos from updates-testing
#   dnf:
#     name: fedora-repos
#     state: latest
#     disablerepo: '*'
#     enablerepo: updates-testing
#     disable_gpg_check: yes

#this does not seem to work, disable_gpg_check not being honored?
# also, i need "dnf update" and this runs "dnf install"
# - name: Install latest DNF
#   dnf:
#     name: dnf
#     state: latest
#     disable_gpg_check: yes
