---
# - name: Install SELinux files
#   dnf:
#     name: libselinux-python
#     state: present
#     disablerepo: fedora-modular-server,fedora-modular-server-updates-testing

- name: Install modular repos
  dnf:
    name: fedora-repos-modular
    state: latest
    disable_gpg_check: yes

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
 

